name: JobM → Google Sheet (Cron)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: jobm-cron
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          EDOCLITE_USER: ${{ secrets.EDOCLITE_USER }}
          EDOCLITE_PASS: ${{ secrets.EDOCLITE_PASS }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python scrape.py

      - name: List files (debug)
        run: |
          echo "workspace=$GITHUB_WORKSPACE"
          pwd
          ls -la
          ls -la output || true
          find "$GITHUB_WORKSPACE" -maxdepth 2 -type d -name "output" -print || true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-output
          path: ${{ github.workspace }}/output
          if-no-files-found: warn
